import { randomUUID } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import type { AuthenticatedUser } from "../types.js";
import { quoteIdentifier } from "../db/migrations.js";

export interface ActionPlan { id: string; source: string; plan: string; steps: unknown[]; revision: number; status: "draft" | "approved"; approvedAt: string | null; executionStatus: "succeeded" | "attention" | null; finalReportHtml: string | null; errorLog: string | null; executedAt: string | null; updatedAt: string; }
interface Row { id: string; source_document: string; plan_text: string; steps: unknown[]; revision: number; status: "draft" | "approved"; approved_at: Date | null; execution_status: "succeeded" | "attention" | null; final_report_html: string | null; error_log: string | null; executed_at: Date | null; updated_at: Date; }
const asPlan = (row: Row): ActionPlan => ({ id: row.id, source: row.source_document, plan: row.plan_text, steps: row.steps, revision: row.revision, status: row.status, approvedAt: row.approved_at?.toISOString() ?? null, executionStatus: row.execution_status, finalReportHtml: row.final_report_html, errorLog: row.error_log, executedAt: row.executed_at?.toISOString() ?? null, updatedAt: row.updated_at.toISOString() });

export class ActionPlanNotFoundError extends Error { constructor() { super("Action plan not found"); this.name = "ActionPlanNotFoundError"; } }
export class ActionPlanImmutableError extends Error { constructor() { super("Approved action plans are immutable"); this.name = "ActionPlanImmutableError"; } }

export class PostgresActionPlanStore {
  readonly #pool: Pool; readonly #table: string;
  constructor(pool: Pool, schemaName = "flowpilot_app") { this.#pool = pool; this.#table = `${quoteIdentifier(schemaName)}.report_action_plans`; }
  async #owned<T>(user: AuthenticatedUser, operation: (client: PoolClient) => Promise<T>) { const client = await this.#pool.connect(); try { await client.query("BEGIN"); await client.query("SELECT set_config('flowpilot.tenant_id',$1,true), set_config('flowpilot.subject_id',$2,true)", [user.tenantId, user.subject]); const result = await operation(client); await client.query("COMMIT"); return result; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
  async create(user: AuthenticatedUser, source: string, plan: string, steps: unknown[]) { return this.#owned(user, async (client) => { const result = await client.query<Row>(`INSERT INTO ${this.#table} (id,tenant_id,subject_id,source_document,plan_text,steps) VALUES ($1,$2,$3,$4,$5,$6) RETURNING *`, [randomUUID(), user.tenantId, user.subject, source, plan, JSON.stringify(steps)]); return asPlan(result.rows[0]); }); }
  async update(user: AuthenticatedUser, id: string, plan: string) { return this.#owned(user, async (client) => { const result = await client.query<Row>(`UPDATE ${this.#table} SET plan_text=$2, steps='[]'::jsonb, revision=revision+1, updated_at=now() WHERE id=$1 AND status='draft' RETURNING *`, [id, plan]); if (result.rows[0]) return asPlan(result.rows[0]); const exists = await client.query<Row>(`SELECT * FROM ${this.#table} WHERE id=$1`, [id]); if (!exists.rows[0]) throw new ActionPlanNotFoundError(); throw new ActionPlanImmutableError(); }); }
  async approve(user: AuthenticatedUser, id: string, revision: number) { return this.#owned(user, async (client) => { const result = await client.query<Row>(`UPDATE ${this.#table} SET status='approved', approved_at=now(), updated_at=now() WHERE id=$1 AND status='draft' AND revision=$2 AND jsonb_array_length(steps) > 0 RETURNING *`, [id, revision]); if (result.rows[0]) return asPlan(result.rows[0]); const exists = await client.query<Row>(`SELECT * FROM ${this.#table} WHERE id=$1`, [id]); if (!exists.rows[0]) throw new ActionPlanNotFoundError(); throw new ActionPlanImmutableError(); }); }
  async findApproved(user: AuthenticatedUser, id: string) { return this.#owned(user, async (client) => { const result = await client.query<Row>(`SELECT * FROM ${this.#table} WHERE id=$1 AND status='approved'`, [id]); return result.rows[0] ? asPlan(result.rows[0]) : undefined; }); }
  async findDraft(user: AuthenticatedUser, id: string) { return this.#owned(user, async (client) => { const result = await client.query<Row>(`SELECT * FROM ${this.#table} WHERE id=$1 AND status='draft'`, [id]); return result.rows[0] ? asPlan(result.rows[0]) : undefined; }); }
  async updateSteps(user: AuthenticatedUser, id: string, steps: unknown[]) { return this.#owned(user, async (client) => { const result = await client.query<Row>(`UPDATE ${this.#table} SET steps=$2, revision=revision+1, updated_at=now() WHERE id=$1 AND status='draft' RETURNING *`, [id, JSON.stringify(steps)]); if (result.rows[0]) return asPlan(result.rows[0]); throw new ActionPlanNotFoundError(); }); }
  async recordExecution(user: AuthenticatedUser, id: string, outcome: { status: "succeeded" | "attention"; html: string; errorLog: string | null }) { return this.#owned(user, async (client) => { const result = await client.query<Row>(`UPDATE ${this.#table} SET execution_status=$2, final_report_html=$3, error_log=$4, executed_at=now(), updated_at=now() WHERE id=$1 AND status='approved' RETURNING *`, [id, outcome.status, outcome.html, outcome.errorLog]); if (result.rows[0]) return asPlan(result.rows[0]); throw new ActionPlanNotFoundError(); }); }
}
